language: cpp

script:
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Coverage -DCPACK_GENERATOR="TGZ"
- cmake --build _build
- cd _build
- wget https://raw.githubusercontent.com/mikaelkg/HitchhikersGuideMachineLearning/master/iris_df.csv
- cd ..
- cmake --build _build --target install
- cmake --build _build --target unit_tests_coverage 
- cmake --build _build --target package
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - lcov
      - graphviz
